name: Cypress

on: 
  push:
    branches:
    - main

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Python server
        run: |
          python manage.py migrate
          nohup python manage.py runserver 127.0.0.1:8080 &

      - name: Wait for server to be ready
        run: npx wait-on http://127.0.0.1:8080

      - name: Install Node.js (for Cypress)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cypress and dependencies
        run: |
          npm install

      - name: Run Cypress tests on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
            browser: ${{ matrix.browser }}
