name: Google Auth & Docker Push to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: symbolic-gift-458207-n6
  REGION: europe-west1
  REPOSITORY: isen-python-app            # Artifact Registry Repository
  SERVICE_NAME: isen-python-app-service  # Cloud Run Service Name

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag Docker image
        run: |
          docker tag my-app ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/my-app:latest

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/my-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/my-app:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --quiet
      
      - name: Wait for the app to be fully deployed
        run: |
          sleep 10
        
#      - name: ZAP Security Scan
#        run: |
#          # Start ZAP proxy
#          docker run -d -p 8080:8080 owasp/zap2docker-stable
          # Wait for ZAP to be fully ready
#          sleep 30
          # Run ZAP Baseline scan against the deployed Cloud Run service URL
#          docker run --network host owasp/zap2docker-stable zap-baseline.py -t http://${{ env.SERVICE_NAME }}.a.run.app
          
#      - name: Upload ZAP Report
#        uses: actions/upload-artifact@v3
#        with:
#          name: zap-report
#          path: zap-report.json
