name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Check dockerfiles with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          format: json
          verbose: true
          strict-labels: true
          failure-threshold: warning
          trusted-registry: repo.domain.com
          files: Dockerfile