name: Hadolint

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"