name: Hadolint

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          failure-threshold: warning
          format: codeclimate