name: Generate and Scan SBOM

on: push

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.15.4
        with:
          path: .
          output-file: project-sbom.syft.json
          format: syft-json

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@v6
        with:
          sbom: project-sbom.syft.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: sbom
          path: project-sbom.syft.json



